### ISSUE TITLE
Header does not get restored to original size

### ISSUE THREAD

**Issue by EsoCoding** [ThemeZee/poseidon#1]
I'm experiencing a problem with the sticky-header. When not logged in, and first scrolling down and then to the top. The original header size does not get restored to default size. When logged it in and having the wp-admin bar on top, it works just like it should. It happened in Chrome, Firefox. Not tested in other browsers yet.

**Comment by Netzberufler** [comment]
Thanks for letting us know. We will try to fix that issue with one of the next updates.

**Comment by EsoCoding** [comment]
After some debugging, i found out that when removing this line from header.php file, the sticky header bar starts working like it should work

`		<div id="header-top" class="header-bar-wrap"><?php do_action( 'poseidon_header_bar' ); ?></div>`

**Comment by Netzberufler** [comment]
Fixed with https://github.com/ThemeZee/poseidon/commit/cc2ff9acf0e1dadf2fb9c64fedb30e7222245bc0
